### ISSUE TITLE
Issues with slowpics2bbcode.user.js

### ISSUE THREAD

**Issue by FonduemangVI** [L4GSP1KE/Userscripts#3]
Hey it looks like ptpimg may have changed something on their end as the script no longer works. Seems to just hang forever.
Would you be able to take a look when you have time please

**Comment by sirius-sama** [comment]
Their service is lagging these days, even manual uploads are stuck while uploading.

**Comment by FonduemangVI** [comment]
Yeah I've tested a few times, and nothing is coming through at all. I'll see if I can troubleshoot a bit further

**Comment by L4GSP1KE** [comment]
Ptpimg is having issues, especially with their link upload which this uses. Reopen if issues are still occurring once ptpimg gets going again. Removing the ptpimg api key will keep the script working with slowpics image links

**Comment by FonduemangVI** [comment]
Thanks for the update. I'll see how it goes
